const SET_USER_NAME = 'SET_USER_NAME';
const SET_ALL_ACTIVITIES = 'SET_ALL_ACTIVITIES';
const GET_ACTIVITIES = 'GET_ACTIVITIES';
const SET_LOADING = "SET_LOADING";
const ORDER_ACTIVITIES = "ORDER_ACTIVITIES"

module.exports = {
    SET_USER_NAME,
    SET_ALL_ACTIVITIES,
    GET_ACTIVITIES,
    SET_LOADING,
    ORDER_ACTIVITIES,
}